/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#d1d5db",
        "inverse-on-surface": "#0b1c30",
        "tertiary-fixed": "#4b5563",
        "secondary-fixed": "#9ca3af",
        "tertiary-container": "#374151",
        "surface-container-highest": "#4b5563",
        "outline": "#6b7280",
        "on-error-container": "#ffdad6",
        "error": "#ef4444",
        "on-secondary-fixed": "#ffffff",
        "background": "#111827",
        "surface-bright": "#374151",
        "on-primary-fixed": "#ffffff",
        "outline-variant": "#4b5563",
        "secondary-fixed-dim": "#6b7280",
        "surface-tint": "#ffffff",
        "primary-container": "#4b5563",
        "on-secondary": "#ffffff",
        "secondary-container": "#374151",
        "on-secondary-fixed-variant": "#ffffff",
        "on-primary-container": "#ffffff",
        "primary-fixed-dim": "#9ca3af",
        "on-background": "#ffffff",
        "surface-container": "#1f2937",
        "surface": "#111827",
        "tertiary": "#d1d5db",
        "error-container": "#7f1d1d",
        "on-tertiary-fixed": "#ffffff",
        "on-primary": "#111827",
        "surface-container-high": "#374151",
        "on-tertiary-container": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#9ca3af",
        "inverse-surface": "#f3f4f6",
        "primary": "#ffffff",
        "on-tertiary-fixed-variant": "#ffffff",
        "surface-variant": "#374151",
        "secondary": "#ffffff",
        "on-surface": "#ffffff",
        "primary-fixed": "#ffffff",
        "surface-container-lowest": "#030712",
        "on-primary-fixed-variant": "#ffffff",
        "surface-container-low": "#111827",
        "on-tertiary": "#111827",
        "on-secondary-container": "#ffffff",
        "surface-dim": "#1f2937",
        "inverse-primary": "#111827"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "0.5rem",
        "stack-lg": "2rem",
        "container-max": "1280px",
        "stack-md": "1rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2.5rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Manrope"],
        "headline-lg": ["Manrope"],
        "headline-xl": ["Manrope"],
        "label-sm": ["JetBrains Mono"],
        "transcription-text": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "transcription-text": ["16px", {"lineHeight": "32px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}